version: "3.3"
services:
  db:
    container_name: postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
