version: "3.5"

networks:
  postgres_db_network:
    name: postgres_db_network
    driver: bridge

services:
  db:
    container_name: postgres_db
    image: postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres_db_network
      
volumes:
  db:
    driver: local
